site_name: Utils
site_url: "https://Evxry_utils.src"
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: blue
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: blue
  icon:
    logo: material/code-tags
  favicon : docs/b.ico
  features:
    - navigation.footer



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - abbr

extra:
  social:
    - icon: simple/roblox
      link: https://www.roblox.com/users/3813642140/profile

copyright: Copyright &copy; 2025 evxry_ll